#' Create a pool of connections
#'
#' Use a list of options (usually created through running \code{credentials_extract})
#' to create a pool of connections to the psql database.
#' @param options_list A list of options for connecting to a database, usually generated by calling \code{credentials_extract()}
#' @param use_sqlite Whether to use SQLite; alternative is PostgreSQL
#' @import RPostgreSQL
#' @import pool
#' @import DBI
#' @import RSQLite
#' @export

# This function is used in conjunction with credentials_extract() (above)
# and fetch_db() (below)
create_pool <- function(options_list,
                        use_sqlite = FALSE){

  # Establish connection with database
  if(use_sqlite){
    options_list$drv <- DBI::dbDriver("SQLite")
  } else {
    options_list$drv <- DBI::dbDriver("PostgreSQL")
  }
  out <- do.call(dbPool, options_list)

  # Return the connection object
  return(out)
}
