#' Create a pool of connections
#'
#' Use a list of options (usually created through running \code{credentials_extract})
#' to create a pool of connections to the psql database.
#' @param options_list A list of options for connecting to a database, usually generated by calling \code{credentials_extract()}
#' @import RPostgreSQL
#' @import pool
#' @export

# This function is used in conjunction with credentials_extract() (above)
# and fetch_db() (below)
create_pool <- function(options_list){

  # Establish connection with database
  options_list$drv <- dbDriver("PostgreSQL")
  out <- do.call(dbPool, options_list)

  # Return the connection object
  return(out)
}
